using System.Collections.Generic;
using System.IO;
using UnityEditor;

namespace ODDGames.Html2Uxml.Editor
{
    // SVGImporter defaults to svgType=VectorImage (3) on first import, but
    // UI Toolkit's `background-image: url(...)` cannot render a VectorImage
    // — labels show as a yellow warning triangle. Force Texture2D (2) on
    // SVGs the converter emitted.
    //
    // SVGImporter is a ScriptedImporter that reads its settings from the
    // .meta before OnPreprocessAsset gets a chance to mutate them, so this
    // runs as a post-pass: detect imported SVGs in converter output dirs,
    // flip svgType to 2 via SerializedObject, then SaveAndReimport. A
    // static guard prevents the SaveAndReimport from looping.
    public sealed class Html2UxmlSvgPostprocessor : AssetPostprocessor
    {
        const int SvgType_Texture2D = 2;
        // ViewportOptions.PreserveViewport — keeps the SVG viewBox padding
        // when baking the texture, so the rasterised ink fills the same
        // fraction of the element box as it does in Chrome. The default
        // (DontPreserve) tight-crops to the ink bounding box, which makes
        // small centred icons (e.g. a diamond with 2px viewBox margin)
        // look larger and visibly off-centre compared to the HTML render.
        const int ViewportOptions_PreserveViewport = 1;
        static readonly HashSet<string> InFlight = new HashSet<string>();

        static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths)
        {
            if (importedAssets == null) return;
            foreach (string assetPath in importedAssets)
            {
                if (string.IsNullOrEmpty(assetPath)) continue;
                if (!assetPath.EndsWith(".svg", System.StringComparison.OrdinalIgnoreCase))
                    continue;
                if (InFlight.Contains(assetPath)) continue;
                if (!IsConverterOutput(assetPath)) continue;

                var importer = AssetImporter.GetAtPath(assetPath);
                if (importer == null) continue;
                if (importer.GetType().Name != "SVGImporter") continue;

                var so = new SerializedObject(importer);
                var svgTypeProp = so.FindProperty("m_SvgType");
                if (svgTypeProp == null) continue;
                var viewportProp = so.FindProperty("m_ViewportOptions");

                bool needsUpdate = svgTypeProp.intValue != SvgType_Texture2D
                    || (viewportProp != null && viewportProp.intValue != ViewportOptions_PreserveViewport);
                if (!needsUpdate) continue;

                svgTypeProp.intValue = SvgType_Texture2D;
                if (viewportProp != null)
                    viewportProp.intValue = ViewportOptions_PreserveViewport;
                so.ApplyModifiedPropertiesWithoutUndo();

                InFlight.Add(assetPath);
                try { importer.SaveAndReimport(); }
                finally { InFlight.Remove(assetPath); }
            }
        }

        // Converter writes SVGs to <bundle>/Images/<name>.svg next to a
        // generated .uxml whose header carries `source:` pointing at the
        // origin HTML. Match on that to avoid touching unrelated SVGs.
        static bool IsConverterOutput(string svgAssetPath)
        {
            string dir = Path.GetDirectoryName(svgAssetPath);
            if (string.IsNullOrEmpty(dir)) return false;
            string parent = Path.GetDirectoryName(dir);
            if (string.IsNullOrEmpty(parent)) return false;
            string[] uxmls;
            try { uxmls = Directory.GetFiles(parent, "*.uxml"); }
            catch { return false; }
            foreach (string uxml in uxmls)
            {
                string head;
                try
                {
                    using (var sr = new StreamReader(uxml))
                    {
                        char[] buf = new char[512];
                        int n = sr.Read(buf, 0, buf.Length);
                        head = new string(buf, 0, n);
                    }
                }
                catch { continue; }
                if (head.IndexOf("AUTOGENERATED FROM", System.StringComparison.Ordinal) >= 0)
                    return true;
            }
            return false;
        }
    }
}
