// SPDX-License-Identifier: MIT
//
// AssetWriter — bundle-output entry point for the C# converter.
// Mirrors html2uxml/assets.py::collect_and_rewrite + inject_image_aspect_ratios
// + the cli.py bundle-writer logic that produces:
//   <bundle>/UI/<base>.uxml
//   <bundle>/UI/<base>.uss
//   <bundle>/UI/Images/...      (referenced images)
//   <bundle>/UI/Fonts/...       (downloaded / extracted fonts)
//   <bundle>/Src/<base>.html    (copy of the source HTML)
//
// Both .uxml and .uss are seeded with a "AUTOGENERATED FROM Src/<base>.html"
// banner so re-conversion and pixel diffs can locate the input.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace ODDGames.Html2Uxml.Editor.Converter.Assets
{
    public sealed class AssetReport
    {
        public List<string> Copied = new List<string>();
        public List<string> Downloaded = new List<string>();
        public List<(string subject, string reason)> Failed = new List<(string, string)>();
    }

    public static class AssetWriter
    {
        public sealed class WriteOptions
        {
            // Bundle root (parent of UI/ and Src/).
            public string OutputDir;
            // Base filename, e.g. "foo" -> foo.uxml, foo.uss, Src/foo.html.
            public string BaseName;
            // Optional: copy this on-disk source HTML into Src/. When null
            // we still write Src/<base>.html using the provided UXML payload's
            // origin if SourceHtmlText is set.
            public string SourceHtmlPath;
            // Inline source HTML text — used when the source isn't a file
            // (e.g. converting a URL the user hands the importer).
            public string SourceHtmlText;
            public bool BundleAssets = true;
            public bool DownloadRemoteAssets;
            public bool DownloadFonts = true;
            public bool UseTextcoreFontAssets;
            // url(...) references that already point to projectSubdir keep
            // their text. Default matches Python.
            public string ProjectImagesSubdir = "Images";
            public TimeSpan Timeout = TimeSpan.FromSeconds(8);
            // When true, prepend the "AUTOGENERATED FROM Src/<base>.html"
            // banners onto the .uxml/.uss before writing.
            public bool EmitAutogenBanner = true;
            // When true, write <OutputDir>/<BaseName>.uxml + .uss directly
            // (no UI/, Src/, Images/ subfolders). Used by the ScriptedImporter
            // so generated files appear next to the source HTML inside the
            // user's project. Asset bundling + Src/ copy are skipped.
            public bool SiblingOutput;
        }

        public sealed class WriteResult
        {
            public string UxmlPath;
            public string UssPath;
            public string SourceCopyPath;
            public string ImagesDir;
            public string FontsDir;
            public AssetReport AssetReport;
            public List<string> Warnings = new List<string>();
        }

        // Single entry point. Writes the bundle to disk, copies/downloads any
        // referenced url(...) targets, and rewrites the USS so url() refs land
        // on the bundle-relative paths.
        //
        //   uxml          : UXML text already produced by the converter.
        //   uss           : USS text already produced by the converter.
        //   sourceHtmlBaseDir: where to resolve relative url() / src= refs
        //                   from. Pass null for URL inputs.
        public static WriteResult Write(
            WriteOptions opt,
            string uxml,
            string uss,
            string sourceHtmlBaseDir)
        {
            if (opt == null) throw new ArgumentNullException(nameof(opt));
            if (string.IsNullOrEmpty(opt.OutputDir)) throw new ArgumentException("OutputDir required");
            if (string.IsNullOrEmpty(opt.BaseName)) throw new ArgumentException("BaseName required");

            var result = new WriteResult { AssetReport = new AssetReport() };

            string finalUss = uss ?? string.Empty;
            string finalUxml = uxml ?? string.Empty;

            // ---- Sibling mode: write <OutputDir>/<BaseName>.{uxml,uss}
            // next to the source HTML. Skips UI/Src/Images/Fonts subdirs.
            // Used by Html2UxmlHtmlImporter so generated assets land in the
            // same Unity folder as the .html. Bundling/font fetch are off.
            if (opt.SiblingOutput)
            {
                Directory.CreateDirectory(opt.OutputDir);
                string siblingRef = (opt.SourceHtmlPath != null
                    ? Path.GetFileName(opt.SourceHtmlPath)
                    : opt.BaseName + ".html");
                if (opt.EmitAutogenBanner)
                {
                    finalUxml = PrependUxmlBanner(finalUxml, siblingRef);
                    finalUss = PrependUssBanner(finalUss, siblingRef);
                }
                string uxmlPathS = Path.Combine(opt.OutputDir, opt.BaseName + ".uxml");
                string ussPathS  = Path.Combine(opt.OutputDir, opt.BaseName + ".uss");
                WriteSiblingAndWarn(uxmlPathS, finalUxml, result.Warnings);
                WriteSiblingAndWarn(ussPathS,  finalUss,  result.Warnings);
                result.UxmlPath = uxmlPathS;
                result.UssPath  = ussPathS;
                return result;
            }

            // ---- Bundle mode: full UI/Src/Images/Fonts layout (default).
            string uiDir = Path.Combine(opt.OutputDir, "UI");
            string srcDir = Path.Combine(opt.OutputDir, "Src");
            string imagesDir = Path.Combine(uiDir, opt.ProjectImagesSubdir);
            string fontsDir = Path.Combine(uiDir, "Fonts");
            Directory.CreateDirectory(uiDir);
            Directory.CreateDirectory(srcDir);
            result.ImagesDir = imagesDir;
            result.FontsDir = fontsDir;

            // 1. Bundle url(...) refs from the USS into UI/Images/.
            if (opt.BundleAssets)
            {
                Directory.CreateDirectory(imagesDir);
                finalUss = CollectAndRewrite(
                    finalUss,
                    sourceHtmlBaseDir,
                    imagesDir,
                    opt.ProjectImagesSubdir,
                    opt.DownloadRemoteAssets,
                    opt.Timeout,
                    result.AssetReport,
                    result.Warnings);
                finalUss = InjectImageAspectRatios(finalUss, imagesDir, opt.ProjectImagesSubdir);
            }

            // 2. Write source HTML copy + breadcrumb.
            string sourceCopyPath = Path.Combine(srcDir, opt.BaseName + ".html");
            string sourceText = ResolveSourceHtmlText(opt);
            if (sourceText != null)
                File.WriteAllText(sourceCopyPath, sourceText, EncodingUtf8NoBom);
            result.SourceCopyPath = sourceCopyPath;
            string sourceRef = "Src/" + Path.GetFileName(sourceCopyPath);

            // 3. Optionally prepend AUTOGENERATED banners.
            if (opt.EmitAutogenBanner)
            {
                finalUxml = PrependUxmlBanner(finalUxml, sourceRef);
                finalUss = PrependUssBanner(finalUss, sourceRef);
            }

            string uxmlPath = Path.Combine(uiDir, opt.BaseName + ".uxml");
            string ussPath = Path.Combine(uiDir, opt.BaseName + ".uss");
            File.WriteAllText(uxmlPath, finalUxml, EncodingUtf8NoBom);
            File.WriteAllText(ussPath, finalUss, EncodingUtf8NoBom);
            result.UxmlPath = uxmlPath;
            result.UssPath = ussPath;
            return result;
        }

        // Sibling-mode write: skip the disk write when on-disk bytes already
        // match. Warn on byte-difference overwrite so the user knows their
        // hand-edits (or another author's output) just got replaced.
        static void WriteSiblingAndWarn(string path, string content, List<string> warnings)
        {
            byte[] newBytes = EncodingUtf8NoBom.GetBytes(content ?? string.Empty);
            if (File.Exists(path))
            {
                byte[] existing;
                try { existing = File.ReadAllBytes(path); }
                catch (IOException) { existing = null; }
                if (existing != null && BytesEqual(existing, newBytes))
                    return; // identical — no write, no warning.
                warnings.Add(
                    $"overwriting {Path.GetFileName(path)} (existing bytes differ from generated output)");
            }
            File.WriteAllBytes(path, newBytes);
        }

        static bool BytesEqual(byte[] a, byte[] b)
        {
            if (a == null || b == null) return false;
            if (a.Length != b.Length) return false;
            for (int i = 0; i < a.Length; i++) if (a[i] != b[i]) return false;
            return true;
        }

        // Encoding.UTF8 in C# defaults to *with* BOM, which trips Unity's
        // text importer. Use a no-BOM instance for everything we author.
        public static readonly Encoding EncodingUtf8NoBom = new UTF8Encoding(false);

        private static string ResolveSourceHtmlText(WriteOptions opt)
        {
            if (!string.IsNullOrEmpty(opt.SourceHtmlText))
                return opt.SourceHtmlText;
            if (!string.IsNullOrEmpty(opt.SourceHtmlPath) && File.Exists(opt.SourceHtmlPath))
            {
                try { return File.ReadAllText(opt.SourceHtmlPath); }
                catch (IOException) { return null; }
                catch (UnauthorizedAccessException) { return null; }
            }
            return null;
        }

        // --- collect_and_rewrite -------------------------------------------

        public static string CollectAndRewrite(
            string uss,
            string baseDir,
            string assetsDir,
            string projectSubdir,
            bool downloadRemote,
            TimeSpan timeout,
            AssetReport report,
            List<string> warnings)
        {
            if (string.IsNullOrEmpty(uss)) return uss ?? string.Empty;
            Directory.CreateDirectory(assetsDir);

            return PathBundler.UrlRegex.Replace(uss, m =>
            {
                string raw = m.Groups[1].Value;
                if (string.IsNullOrEmpty(raw)) raw = m.Groups[2].Value;
                if (string.IsNullOrEmpty(raw)) raw = m.Groups[3].Value;
                if (string.IsNullOrEmpty(raw)) return m.Value;

                if (raw.StartsWith("data:", StringComparison.OrdinalIgnoreCase))
                {
                    var decoded = PathBundler.DecodeImageDataUri(raw);
                    if (!decoded.HasValue)
                    {
                        report.Failed.Add((PathBundler.TruncateForReport(raw), "unsupported data URI"));
                        return m.Value;
                    }
                    var (data, ext) = decoded.Value;
                    string targetName = "embedded-" + PathBundler.Sha1Hex(data, 12) + ext;
                    targetName = PathBundler.WriteBytesSmart(
                        assetsDir, targetName, data, ImageTranscoder.MaybeTranscodeToPng, warnings);
                    report.Copied.Add("data:");
                    return $"url(\"{projectSubdir}/{targetName}\")";
                }

                // Already a project-relative ref (e.g. emitted by SVG inlining).
                if (raw.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase)
                    || raw.StartsWith("Assets\\", StringComparison.OrdinalIgnoreCase))
                {
                    return m.Value;
                }

                // Already inside our images bundle? Verify the file is on disk.
                string rel = PathBundler.AssetRefToRelativePath(raw, projectSubdir);
                if (rel != null)
                {
                    if (!File.Exists(Path.Combine(assetsDir, rel)))
                        report.Failed.Add((raw, "file not found"));
                    return m.Value;
                }

                if (raw.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
                    || raw.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
                {
                    if (!downloadRemote)
                    {
                        report.Failed.Add((raw, "remote (download disabled)"));
                        return m.Value;
                    }
                    string local = DownloadAsset(raw, assetsDir, timeout, report, warnings);
                    if (local == null) return m.Value;
                    return $"url(\"{projectSubdir}/{local}\")";
                }

                // Relative or absolute filesystem path.
                string srcPath = raw;
                if (!Path.IsPathRooted(srcPath) && !string.IsNullOrEmpty(baseDir))
                    srcPath = Path.Combine(baseDir, raw);
                try
                {
                    if (!File.Exists(srcPath))
                    {
                        report.Failed.Add((raw, "file not found"));
                        return m.Value;
                    }
                    string targetName = PathBundler.SafeName(Path.GetFileName(srcPath));
                    byte[] data = File.ReadAllBytes(srcPath);
                    targetName = PathBundler.WriteBytesSmart(
                        assetsDir, targetName, data, ImageTranscoder.MaybeTranscodeToPng, warnings);
                    report.Copied.Add(raw);
                    return $"url(\"{projectSubdir}/{targetName}\")";
                }
                catch (IOException e)
                {
                    report.Failed.Add((raw, e.Message));
                    return m.Value;
                }
                catch (UnauthorizedAccessException e)
                {
                    report.Failed.Add((raw, e.Message));
                    return m.Value;
                }
            });
        }

        private static string DownloadAsset(
            string url, string destDir, TimeSpan timeout, AssetReport report, List<string> warnings)
        {
            string slug = url;
            int slash = slug.LastIndexOf('/');
            if (slash >= 0) slug = slug.Substring(slash + 1);
            int q = slug.IndexOf('?');
            if (q >= 0) slug = slug.Substring(0, q);
            string name = PathBundler.SafeName(slug);
            if (string.IsNullOrEmpty(name) || name == "asset")
                name = PathBundler.Sha1HexUtf8(url);
            try
            {
                byte[] data = FontFetcher.HttpDownload(url, timeout);
                string written = PathBundler.WriteBytesSmart(
                    destDir, name, data, ImageTranscoder.MaybeTranscodeToPng, warnings);
                report.Downloaded.Add(url);
                return written;
            }
            catch (Exception e)
            {
                report.Failed.Add((url, e.Message));
                return null;
            }
        }

        // --- inject_image_aspect_ratios ------------------------------------

        // Walk every USS rule body and add `aspect-ratio: W/H;` next to a
        // background-image whose target file we can sniff dimensions from.
        // Mirrors assets.py::inject_image_aspect_ratios — UI Toolkit doesn't
        // preserve intrinsic image ratios, so converted <img> tags need this.
        public static string InjectImageAspectRatios(
            string uss, string assetsDir, string projectSubdir)
        {
            if (string.IsNullOrEmpty(uss)) return uss ?? string.Empty;
            var ruleRe = new Regex(@"(?<head>[^{]+)\{(?<body>[^{}]*)\}", RegexOptions.Multiline);

            return ruleRe.Replace(uss, m =>
            {
                string body = m.Groups["body"].Value;
                if (body.IndexOf("aspect-ratio", StringComparison.OrdinalIgnoreCase) >= 0)
                    return m.Value;
                var urlMatch = PathBundler.UrlRegex.Match(body);
                if (!urlMatch.Success) return m.Value;
                string reference = urlMatch.Groups[1].Value;
                if (string.IsNullOrEmpty(reference)) reference = urlMatch.Groups[2].Value;
                if (string.IsNullOrEmpty(reference)) reference = urlMatch.Groups[3].Value;
                string rel = PathBundler.AssetRefToRelativePath(reference, projectSubdir);
                if (rel == null) return m.Value;
                var dims = PathBundler.SniffImageDimensions(Path.Combine(assetsDir, rel));
                if (!dims.HasValue) return m.Value;
                int w = dims.Value.width, h = dims.Value.height;
                if (w <= 0 || h <= 0) return m.Value;
                double ratio = (double)w / h;
                string ratioText = ratio.ToString("g", System.Globalization.CultureInfo.InvariantCulture);

                var lines = body.Replace("\r\n", "\n").Split('\n');
                var output = new List<string>(lines.Length + 1);
                bool inserted = false;
                for (int i = 0; i < lines.Length; i++)
                {
                    string line = lines[i];
                    output.Add(line);
                    if (!inserted && line.IndexOf("background-image", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        string indent = "    ";
                        var indentMatch = Regex.Match(line, @"^(\s*)");
                        if (indentMatch.Success && !string.IsNullOrEmpty(indentMatch.Groups[1].Value))
                            indent = indentMatch.Groups[1].Value;
                        output.Add(indent + "aspect-ratio: " + ratioText + ";");
                        inserted = true;
                    }
                }
                if (!inserted)
                    output.Add("    aspect-ratio: " + ratioText + ";");
                return m.Groups["head"].Value + "{" + string.Join("\n", output) + "}";
            });
        }

        // --- banners --------------------------------------------------------

        public static string PrependUxmlBanner(string uxml, string sourceRef)
        {
            string banner =
                "<!-- ============================================================== -->\n" +
                "<!-- AUTOGENERATED FROM " + sourceRef + "                                -->\n" +
                "<!-- DO NOT EDIT THIS FILE - your changes will be overwritten on    -->\n" +
                "<!-- the next conversion. Edit the source HTML/CSS instead.         -->\n" +
                "<!-- ============================================================== -->\n";
            if (string.IsNullOrEmpty(uxml)) return banner;
            if (!uxml.StartsWith("<?xml", StringComparison.OrdinalIgnoreCase))
                return banner + uxml;
            int nl = uxml.IndexOf('\n');
            if (nl >= 0)
                return uxml.Substring(0, nl + 1) + banner + uxml.Substring(nl + 1);
            return uxml + "\n" + banner;
        }

        public static string PrependUssBanner(string uss, string sourceRef)
        {
            string banner =
                "/* ================================================================ */\n" +
                "/* AUTOGENERATED FROM " + sourceRef + "                                  */\n" +
                "/* DO NOT EDIT THIS FILE - your changes will be overwritten on      */\n" +
                "/* the next conversion. Edit the source HTML/CSS instead.           */\n" +
                "/* ================================================================ */\n";
            return banner + (uss ?? string.Empty);
        }
    }
}
